### ISSUE TITLE
ToDos for 1.0 processes

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-earthengine-driver#34]
**ToDos:**

- [x] first, last: complex implementation
- [x] filter_bands, load_collection: implement common name support
- [ ] merge_cubes: implement overlap resolver (see reduce_dimensions)
- [x] if: JS only, implement ee.Algorithm.If support?
- [x] mean, median, sd, variance: Implement complex reduce
- [x] text_*: JS only, implement native GEE support?
- [x] Remove JS only codes
